version: '3.3'

services:
  db:
    build: ./mysql/
    # image: mysqlcompose
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    
  backend:
    depends_on:
      - db
    build: ./flask/
    # image: flaskcompose
    ports:
      - "5000:5000"
    restart: always
    #BIND MOUNT É O DIRETÓRIO DA PRÓRPIA MÁQUINA
    volumes:
      - "docker-para-desenvolvedores-docker-swarm-e-kubernetes-udemy/5_COMPOSE/6_bind_mount_compose:/app" #PATH COMPLETO windows coloca \\
    networks:
      - dockercompose
  
networks:
  dockercompose: